apiVersion: v1
kind: Service
metadata:
  name: clmglaylog-svc
spec:
  selector:
    app: csvglaylog
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30007